import { isNonEmptyString, isPlainObject, toNumber, uniqueBy } from './strings.js';

const parseHeight = (value) => {
  const match = String(value || '').match(/(\d{3,4})p/i);
  return match ? Number(match[1]) : 0;
};

const parseUrlFromCipher = (format) => {
  const cipher = format?.signatureCipher || format?.signature_cipher || format?.cipher;
  if (!cipher) return null;
  try {
    return new URLSearchParams(cipher).get('url');
  } catch {
    return null;
  }
};

export const normalizeThumbnails = (thumbnails = []) =>
  (Array.isArray(thumbnails) ? thumbnails : [])
    .filter(isPlainObject)
    .map((thumb) => ({
      url: String(thumb.url || ''),
      width: toNumber(thumb.width, 0),
      height: toNumber(thumb.height, 0),
      quality: String(thumb.quality || ''),
    }))
    .filter((thumb) => isNonEmptyString(thumb.url));

export const pickThumbnail = (thumbnails = []) => {
  const normalized = normalizeThumbnails(thumbnails);
  if (!normalized.length) return null;
  return [...normalized].sort((a, b) => (b.width * b.height) - (a.width * a.height))[0];
};

export const normalizeCaptionTrack = (caption = {}) => ({
  label: String(caption.label || caption.name || ''),
  languageCode: String(caption.language_code || caption.languageCode || ''),
  url: String(caption.url || ''),
});

export const normalizeCaptionTracks = (captions = {}) => {
  if (Array.isArray(captions)) return captions.map(normalizeCaptionTrack);
  if (!isPlainObject(captions)) return [];

  const out = [];
  for (const [languageCode, tracks] of Object.entries(captions)) {
    if (!Array.isArray(tracks)) continue;
    for (const track of tracks) {
      if (!isPlainObject(track)) continue;
      out.push(normalizeCaptionTrack({
        label: track.name || track.label || languageCode,
        languageCode: track.language_code || track.languageCode || languageCode,
        url: track.url || '',
      }));
    }
  }
  return out;
};

export const normalizeVideoItem = (item = {}) => ({
  type: String(item.type || 'video'),
  videoId: String(item.videoId || item.id || ''),
  title: String(item.title || ''),
  author: String(item.author || item.authorName || item.uploader || item.channel || ''),
  authorId: String(item.authorId || item.ucid || item.channel_id || ''),
  authorUrl: String(item.authorUrl || item.channel_url || item.uploader_url || ''),
  authorVerified: Boolean(item.authorVerified),
  description: String(item.description || ''),
  descriptionHtml: String(item.descriptionHtml || item.description_html || ''),
  videoThumbnails: normalizeThumbnails(item.videoThumbnails || item.thumbnails || []),
  lengthSeconds: toNumber(item.lengthSeconds || item.duration, 0),
  viewCount: toNumber(item.viewCount || item.view_count, 0),
  published: toNumber(item.published || item.timestamp || item.release_timestamp, 0),
  publishedText: String(item.publishedText || item.upload_date || ''),
  liveNow: Boolean(item.liveNow || item.is_live),
  paid: Boolean(item.paid),
  premium: Boolean(item.premium),
  isUpcoming: Boolean(item.isUpcoming || item.is_upcoming),
  isListed: item.isListed === undefined ? true : Boolean(item.isListed),
  viewCountText: String(item.viewCountText || item.view_count_text || ''),
  subCountText: String(item.subCountText || item.sub_count_text || ''),
  subCount: toNumber(item.subCount, 0),
  playlistId: String(item.playlistId || ''),
  playlistThumbnail: String(item.playlistThumbnail || item.playlist_thumbnail || ''),
  playlistIndex: toNumber(item.index, 0),
  videoCount: toNumber(item.videoCount, 0),
  url: String(item.url || item.webpage_url || ''),
  autoGenerated: Boolean(item.autoGenerated || item.is_auto_generated),
  hashtags: Array.isArray(item.hashtags) ? item.hashtags : Array.isArray(item.tags) ? item.tags : [],
  keywords: Array.isArray(item.keywords) ? item.keywords : Array.isArray(item.tags) ? item.tags : [],
  captions: Array.isArray(item.captions) ? item.captions : normalizeCaptionTracks(item.subtitles || item.automatic_captions || {}),
  chapters: Array.isArray(item.chapters) ? item.chapters : [],
  relatedVideos: Array.isArray(item.related_videos) ? item.related_videos.map(normalizeVideoItem) : [],
});

export const normalizePlaylistItem = (item = {}) => ({
  type: 'playlist',
  playlistId: String(item.playlistId || item.id || ''),
  title: String(item.title || ''),
  author: String(item.author || ''),
  authorId: String(item.authorId || ''),
  authorUrl: String(item.authorUrl || item.channel_url || item.uploader_url || ''),
  authorVerified: Boolean(item.authorVerified),
  playlistThumbnail: String(item.playlistThumbnail || item.playlist_thumbnail || ''),
  videoCount: toNumber(item.videoCount, 0),
  videos: Array.isArray(item.videos) ? item.videos.map(normalizeVideoItem) : [],
});

export const normalizeChannelItem = (item = {}) => ({
  type: 'channel',
  author: String(item.author || item.name || ''),
  authorId: String(item.authorId || item.ucid || item.id || ''),
  authorUrl: String(item.authorUrl || item.channel_url || item.uploader_url || ''),
  authorThumbnails: normalizeThumbnails(item.authorThumbnails || []),
  description: String(item.description || ''),
  descriptionHtml: String(item.descriptionHtml || item.description_html || ''),
  subCountText: String(item.subCountText || item.subCount || ''),
  subCount: toNumber(item.subCount, 0),
  videoCount: toNumber(item.videoCount, 0),
  autoGenerated: Boolean(item.autoGenerated || item.is_auto_generated),
  authorVerified: Boolean(item.authorVerified),
});

export const normalizeHashtagItem = (item = {}) => ({
  type: 'hashtag',
  title: String(item.title || ''),
  url: String(item.url || item.webpage_url || ''),
  channelCount: toNumber(item.channelCount, 0),
  videoCount: toNumber(item.videoCount, 0),
});

export const normalizeSearchItem = (item = {}) => {
  switch (String(item.type || 'video')) {
    case 'channel':
      return normalizeChannelItem(item);
    case 'playlist':
      return normalizePlaylistItem(item);
    case 'hashtag':
      return normalizeHashtagItem(item);
    default:
      return normalizeVideoItem(item);
  }
};

const isMuxed = (format) =>
  Boolean(format && ((format.vcodec && format.vcodec !== 'none' && format.acodec && format.acodec !== 'none') || (format.mime && format.mime.includes('video') && format.mime.includes('audio'))));

const isVideoOnly = (format) =>
  Boolean(format && ((format.vcodec && format.vcodec !== 'none' && (!format.acodec || format.acodec === 'none')) || (format.mime && format.mime.includes('video') && !format.mime.includes('audio'))));

const isAudioOnly = (format) =>
  Boolean(format && ((format.acodec && format.acodec !== 'none' && (!format.vcodec || format.vcodec === 'none')) || (format.mime && format.mime.includes('audio') && !format.mime.includes('video'))));

const scoreVideo = (format) => [toNumber(format.height, 0), toNumber(format.width, 0), toNumber(format.fps, 0), toNumber(format.tbr, 0), toNumber(format.filesize_approx || format.filesize, 0)];
const scoreAudio = (format) => [toNumber(format.abr, 0), toNumber(format.tbr, 0), toNumber(format.filesize_approx || format.filesize, 0)];

const compareScore = (left, right) => {
  for (let index = 0; index < left.length; index += 1) {
    if (left[index] !== right[index]) return right[index] - left[index];
  }
  return 0;
};

const normalizeFormat = (format) => {
  if (!isPlainObject(format)) return null;
  const mime = String(format.mimeType || format.mime_type || format.type || '').toLowerCase();
  return {
    ...format,
    url: String(format.url || parseUrlFromCipher(format) || ''),
    mime,
    vcodec: String(format.vcodec || '').toLowerCase(),
    acodec: String(format.acodec || '').toLowerCase(),
    width: toNumber(format.width, 0),
    height: toNumber(format.height || parseHeight(format.qualityLabel || format.resolution), 0),
    fps: toNumber(format.fps, 0),
    tbr: toNumber(format.tbr || format.bitrate || format.total_bitrate, 0),
    abr: toNumber(format.abr || format.audioBitrate, 0),
    vbr: toNumber(format.vbr, 0),
    filesize: toNumber(format.filesize, 0),
    filesize_approx: toNumber(format.filesize_approx, 0),
    qualityLabel: String(format.qualityLabel || format.quality_label || format.resolution || ''),
  };
};

export const collectFormats = (raw = {}) => {
  const sources = [
    raw.formatStreams,
    raw.adaptiveFormats,
    raw.adaptive_formats,
    raw.formats,
    raw.requested_formats,
    raw.streamingData?.formats,
    raw.streamingData?.adaptiveFormats,
    raw.streamingData?.adaptive_formats,
    raw.streamingData?.requested_formats,
  ].flat().filter(Boolean);

  const out = [];
  const seen = new Set();

  for (const entry of sources) {
    const normalized = normalizeFormat(entry);
    if (!normalized || !isNonEmptyString(normalized.url)) continue;
    if (seen.has(normalized.url)) continue;
    seen.add(normalized.url);
    out.push(normalized);
  }

  return out;
};

export const choosePlaybackSource = (video = {}) => {
  const formats = collectFormats(video);
  const muxed = [...formats].filter(isMuxed).sort((a, b) => compareScore(scoreVideo(a), scoreVideo(b)))[0] || null;
  if (muxed?.url) {
    return { kind: 'direct', url: muxed.url, source: 'formatStreams' };
  }

  if (isNonEmptyString(video.hlsUrl)) {
    return { kind: 'hls', url: video.hlsUrl, source: 'hlsUrl' };
  }

  const videoOnly = [...formats].filter(isVideoOnly).sort((a, b) => compareScore(scoreVideo(a), scoreVideo(b)))[0] || null;
  const audioOnly = [...formats].filter(isAudioOnly).sort((a, b) => compareScore(scoreAudio(a), scoreAudio(b)))[0] || null;
  if (videoOnly?.url && audioOnly?.url) {
    return { kind: 'dash', videoUrl: videoOnly.url, audioUrl: audioOnly.url, source: 'adaptiveFormats' };
  }

  if (isNonEmptyString(video.dashUrl)) {
    return { kind: 'dashManifest', url: video.dashUrl, source: 'dashUrl' };
  }

  return null;
};

export const dedupeVideos = (videos = []) => uniqueBy(videos, (item) => item.videoId || item.playlistId || item.authorId || item.url || item.title);
