import type { QualityOption, StreamEntry, StreamPayload, StreamSubtitle } from '../../shared/types'
import type { InternalStreamEntry } from './internalEntry'

/** Project internal format metadata down to the client-facing track. */
export function toPublicEntry(entry: InternalStreamEntry | StreamEntry): StreamEntry {
  const out: StreamEntry = { url: entry.url }
  if (entry.isM3u8) out.isM3u8 = true
  if (entry.vcodec) out.vcodec = entry.vcodec
  if (entry.ext) out.ext = entry.ext
  return out
}

function slimQuality(q: QualityOption): QualityOption {
  const out: QualityOption = {
    id: q.id,
    label: q.label,
    isMuxed: q.isMuxed,
    isHls: q.isHls,
    video: toPublicEntry(q.video),
  }
  if (q.height != null) out.height = q.height
  if (q.isAdaptiveHls) out.isAdaptiveHls = true
  if (q.audio) out.audio = toPublicEntry(q.audio)
  return out
}

function slimSubtitle(s: StreamSubtitle): StreamSubtitle {
  const out: StreamSubtitle = {
    languageCode: s.languageCode,
    url: s.url,
  }
  if (s.languageName) out.languageName = s.languageName
  if (s.autoGenerated) out.autoGenerated = true
  return out
}

/** Drop fields the client never reads before the payload leaves the Worker. */
export function slimStreamPayload(payload: StreamPayload): StreamPayload {
  return {
    qualities: payload.qualities.map(slimQuality),
    subtitles: payload.subtitles.map(slimSubtitle),
  }
}
