import type { StreamSubtitle } from '../../shared/types'
import { mediaProxyPath } from '../mediaProxy'
import { asArray, asString, isRecord, requiredString } from '../parse'
import { preferWebVttUrl } from './captions/webvtt'
import { isSafeMediaUrl } from './url'

const SKIP_LANGS = new Set(['live_chat', 'live-chat'])
const LANG_PRIORITY = ['ja', 'en', 'en-US', 'en-GB']

/**
 * Collect and normalize captions from SiaTube stream payload.
 * URLs are rewritten through `/api/media-proxy` for browser CORS.
 */
export function collectSubtitles(source: unknown): StreamSubtitle[] {
  if (!isRecord(source)) return []
  const out: StreamSubtitle[] = []

  walkGroup(source.manualByLanguage, false, out)
  walkGroup(source.automaticByLanguage, true, out)

  return dedupeByLanguage(out)
}

function dedupeByLanguage(items: StreamSubtitle[]): StreamSubtitle[] {
  const seen = new Set<string>()
  const sorted = [...items].sort((a, b) => {
    const ia = LANG_PRIORITY.indexOf(a.languageCode)
    const ib = LANG_PRIORITY.indexOf(b.languageCode)
    return (ia === -1 ? 99 : ia) - (ib === -1 ? 99 : ib)
  })

  const deduped: StreamSubtitle[] = []
  for (const s of sorted) {
    if (seen.has(s.languageCode)) continue
    seen.add(s.languageCode)
    deduped.push(s)
  }
  return deduped
}

function walkGroup(group: unknown, auto: boolean, out: StreamSubtitle[]): void {
  if (!isRecord(group)) return
  for (const value of Object.values(group)) {
    if (!isRecord(value)) continue
    const lang = isRecord(value.language) ? value.language : {}
    const code = requiredString(lang.code, '')
    if (!code || SKIP_LANGS.has(code)) continue

    const captions = asArray(value.captions)
    const preferred =
      captions.find((c) => isRecord(c) && asString(c.ext) === 'vtt') ??
      captions.find((c) => isRecord(c) && asString(c.ext) === 'srt') ??
      captions.find((c) => isRecord(c) && asString(c.url))
    if (!isRecord(preferred)) continue

    const protocol = asString(preferred.protocol)?.toLowerCase() ?? ''
    if (protocol.includes('live_chat')) continue

    let url = asString(preferred.url)
    if (!url || !isSafeMediaUrl(url)) continue
    url = preferWebVttUrl(url)

    out.push({
      languageCode: code,
      languageName: asString(lang.name) ?? asString(preferred.name),
      url: mediaProxyPath(url),
      autoGenerated: auto || asString(preferred.kind) === 'automatic',
    })
  }
}
