import { settings } from '../settings.js';
import { badRequest, notFound } from '../lib/httpError.js';
import { pickThumbnail, normalizeVideoItem, normalizePlaylistItem, normalizeChannelItem } from '../lib/media.js';
import { extractChannelHandle } from '../lib/youtube.js';
import { fetchFromAny, resolveYouTubeUrl } from '../providers/invidious.js';
import { isNonEmptyString } from '../lib/strings.js';

const resolveChannelId = async (input) => {
  const trimmed = String(input || '').trim();
  if (!trimmed) throw badRequest('channel id required');
  if (trimmed.startsWith('UC')) return trimmed;

  const handle = extractChannelHandle(trimmed);
  if (handle) {
    const { data } = await resolveYouTubeUrl(`https://www.youtube.com/${handle}`);
    return String(data.ucid || data.browseId || data.channelId || '');
  }

  return trimmed;
};

const normalizeChannelHeader = (video = {}, channelSearch = {}) => ({
  id: String(channelSearch.authorId || channelSearch.ucid || video.authorId || ''),
  name: String(channelSearch.author || video.author || ''),
  avatar: pickThumbnail(channelSearch.authorThumbnails || video.authorThumbnails || [])?.url || '',
  banner: pickThumbnail(channelSearch.authorBanners || [])?.url || '',
  description: String(channelSearch.description || video.description || ''),
  subCountText: String(channelSearch.subCountText || channelSearch.subCount || ''),
  verified: Boolean(channelSearch.authorVerified),
  autoGenerated: Boolean(channelSearch.autoGenerated),
  videoCount: Number(channelSearch.videoCount || 0),
});

const enrichChannelHeader = async (channelId) => {
  const query = channelId.startsWith('UC') ? channelId : `@${channelId.replace(/^@/, '')}`;
  const [searchResult, videosResult] = await Promise.allSettled([
    fetchFromAny('/api/v1/search', { q: query, type: 'channel', sort: 'relevance', region: settings.region, hl: settings.hl }),
    fetchFromAny(`/api/v1/channels/${encodeURIComponent(channelId)}/videos`, { hl: settings.hl }),
  ]);

  const searchItems = searchResult.status === 'fulfilled' ? searchResult.value.data : [];
  const videoData = videosResult.status === 'fulfilled' ? videosResult.value.data : { videos: [], continuation: '' };

  const channelMatch = Array.isArray(searchItems)
    ? searchItems.find((item) => item.type === 'channel' && (item.authorId === channelId || item.authorId === `/${channelId}` || item.author?.toLowerCase?.() === query.toLowerCase()))
    : null;

  const firstVideo = Array.isArray(videoData.videos) ? videoData.videos[0] : null;
  return { channelMatch, firstVideo };
};

export const fetchChannelPage = async (input, { continuation = '', sortBy = 'newest' } = {}) => {
  const channelId = await resolveChannelId(input);
  if (!isNonEmptyString(channelId)) throw notFound('channel not found');

  const [videosRes, playlistsRes, relatedRes, headerRes] = await Promise.allSettled([
    fetchFromAny(`/api/v1/channels/${encodeURIComponent(channelId)}/videos`, { continuation, sort_by: sortBy, hl: settings.hl }),
    fetchFromAny(`/api/v1/channels/${encodeURIComponent(channelId)}/playlists`, { hl: settings.hl }),
    fetchFromAny(`/api/v1/channels/${encodeURIComponent(channelId)}/channels`, { hl: settings.hl }),
    enrichChannelHeader(channelId),
  ]);

  const videos = videosRes.status === 'fulfilled' ? videosRes.value.data : { videos: [], continuation: '' };
  const playlists = playlistsRes.status === 'fulfilled' ? playlistsRes.value.data : { playlists: [], continuation: '' };
  const related = relatedRes.status === 'fulfilled' ? relatedRes.value.data : { relatedChannels: [], continuation: '' };
  const headerResValue = headerRes.status === 'fulfilled' ? headerRes.value : { channelMatch: null, firstVideo: null };

  const header = normalizeChannelHeader(headerResValue.firstVideo || videos?.videos?.[0] || {}, headerResValue.channelMatch || {});

  return {
    channelId,
    title: header.name || channelId,
    header,
    videos: Array.isArray(videos.videos) ? videos.videos.map((item) => normalizeVideoItem(item)) : [],
    continuation: String(videos.continuation || ''),
    playlists: Array.isArray(playlists.playlists) ? playlists.playlists.map((item) => normalizePlaylistItem(item)) : [],
    playlistsContinuation: String(playlists.continuation || ''),
    relatedChannels: Array.isArray(related.relatedChannels) ? related.relatedChannels.map((item) => normalizeChannelItem(item)) : [],
    relatedContinuation: String(related.continuation || ''),
    sortBy,
  };
};
