import type { StreamSubtitle } from '../../../../shared/types'
import { mediaProxyPath } from '../../../mediaProxy'
import { asArray, asString, isRecord } from '../../../parse'
import { preferWebVttUrl } from '../../captions/webvtt'
import { isSafeMediaUrl } from '../../url'

/**
 * RapidAPI captions.captionTracks → StreamSubtitle[] (official schema).
 * URLs go through media-proxy for CORS / WebVTT.
 */
export function collectRapidCaptions(source: unknown): StreamSubtitle[] {
  if (!isRecord(source)) return []
  const tracks = asArray(source.captionTracks)
  const out: StreamSubtitle[] = []
  const seen = new Set<string>()

  for (const raw of tracks) {
    if (!isRecord(raw)) continue
    const code = asString(raw.languageCode)
    if (!code || seen.has(code)) continue

    let url = asString(raw.baseUrl) ?? asString(raw.url)
    if (!url || !isSafeMediaUrl(url)) continue
    url = preferWebVttUrl(url)

    const name = asString(raw.name)
    const vssId = asString(raw.vssId) ?? ''
    const autoGenerated =
      vssId.startsWith('a.') ||
      raw.kind === 'asr' ||
      /auto-?generated/i.test(name ?? '')

    seen.add(code)
    out.push({
      languageCode: code,
      languageName: name,
      url: mediaProxyPath(url),
      autoGenerated,
    })
  }

  return out
}
