import { useEffect, useRef, useState } from 'react'
import type { QualityOption, StreamSubtitle } from '@shared/types'
import { PLAYBACK_RATES } from './constants'
import { IconCc, IconSettings } from './icons'
import { ChoiceRow, MenuRow, SubPanel } from './PlayerSettingsItems'

type Panel = 'root' | 'speed' | 'quality' | 'subtitle'

function subtitleLabel(track: StreamSubtitle): string {
  return `${track.languageName ?? track.languageCode}${track.autoGenerated ? ' (auto)' : ''}`
}

type PlayerSettingsMenuProps = {
  rate: number
  onRateChange: (rate: number) => void
  qualities: QualityOption[]
  selectedQualityId?: string
  onQualityChange: (id: string) => void
  subtitles: StreamSubtitle[]
  subtitlesEnabled: boolean
  selectedSubtitleUrl?: string
  onSubtitlesEnabledChange: (enabled: boolean) => void
  onSubtitleChange: (url: string) => void
  onOpenChange?: (open: boolean) => void
  /**
   * HLS restricted mode: only quality switching (no speed / captions).
   * Opens the quality panel directly when the gear is clicked.
   */
  qualityOnly?: boolean
  /** While media is loading — menu cannot open. */
  disabled?: boolean
}

export function PlayerSettingsMenu({
  rate,
  onRateChange,
  qualities,
  selectedQualityId,
  onQualityChange,
  subtitles,
  subtitlesEnabled,
  selectedSubtitleUrl,
  onSubtitlesEnabledChange,
  onSubtitleChange,
  onOpenChange,
  qualityOnly = false,
  disabled = false,
}: PlayerSettingsMenuProps) {
  const [open, setOpen] = useState(false)
  const [panel, setPanel] = useState<Panel>('root')
  const rootRef = useRef<HTMLDivElement>(null)

  const setMenuOpen = (next: boolean) => {
    setOpen(next)
    if (!next) setPanel('root')
    else if (qualityOnly) setPanel('quality')
    onOpenChange?.(next)
  }

  useEffect(() => {
    if (!open) return
    const onDoc = (e: MouseEvent) => {
      if (!rootRef.current?.contains(e.target as Node)) setMenuOpen(false)
    }
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setMenuOpen(false)
    }
    document.addEventListener('mousedown', onDoc)
    document.addEventListener('keydown', onKey)
    return () => {
      document.removeEventListener('mousedown', onDoc)
      document.removeEventListener('keydown', onKey)
    }
  }, [open])

  const qualityLabel =
    qualities.find((q) => q.id === selectedQualityId)?.label ??
    qualities[0]?.label ??
    '—'

  const selectedTrack = subtitles.find((s) => s.url === selectedSubtitleUrl)
  const currentSubLabel = !subtitlesEnabled
    ? 'オフ'
    : selectedTrack
      ? subtitleLabel(selectedTrack)
      : subtitles[0]
        ? subtitleLabel(subtitles[0])
        : 'なし'

  return (
    <div ref={rootRef} className="relative" data-controls>
      <button
        type="button"
        aria-label="設定"
        aria-expanded={open}
        className="rounded-full p-2 transition hover:bg-white/10"
        disabled={disabled}
        onClick={(e) => {
          e.stopPropagation()
          if (disabled) return
          setMenuOpen(!open)
        }}
      >
        <IconSettings />
      </button>

      {open ? (
        <div
          className="absolute bottom-full right-0 mb-2 w-56 overflow-hidden rounded-lg bg-[#212121]/95 text-sm text-white shadow-xl backdrop-blur-sm"
          onClick={(e) => e.stopPropagation()}
        >
          {panel === 'root' && !qualityOnly && (
            <ul className="py-1">
              <MenuRow
                label="再生速度"
                value={rate === 1 ? '通常' : `${rate}`}
                onClick={() => setPanel('speed')}
              />
              <MenuRow
                label="字幕"
                value={currentSubLabel}
                icon={<IconCc className="h-4 w-4" />}
                onClick={() => setPanel('subtitle')}
                disabled={!subtitles.length}
              />
              <MenuRow
                label="画質"
                value={qualityLabel}
                onClick={() => setPanel('quality')}
                disabled={!qualities.length}
              />
            </ul>
          )}

          {panel === 'speed' && (
            <SubPanel title="再生速度" onBack={() => setPanel('root')}>
              {PLAYBACK_RATES.map((r) => (
                <ChoiceRow
                  key={r}
                  label={r === 1 ? '通常' : String(r)}
                  selected={rate === r}
                  onClick={() => {
                    onRateChange(r)
                    setMenuOpen(false)
                  }}
                />
              ))}
            </SubPanel>
          )}

          {panel === 'quality' && (
            <SubPanel
              title="画質"
              onBack={qualityOnly ? undefined : () => setPanel('root')}
            >
              {qualities.map((q) => (
                <ChoiceRow
                  key={q.id}
                  label={q.label}
                  selected={q.id === selectedQualityId}
                  onClick={() => {
                    onQualityChange(q.id)
                    setMenuOpen(false)
                  }}
                />
              ))}
            </SubPanel>
          )}

          {panel === 'subtitle' && (
            <SubPanel title="字幕" onBack={() => setPanel('root')}>
              <ChoiceRow
                label="オフ"
                selected={!subtitlesEnabled}
                onClick={() => {
                  onSubtitlesEnabledChange(false)
                  setMenuOpen(false)
                }}
              />
              {subtitles.map((track) => (
                <ChoiceRow
                  key={track.url}
                  label={subtitleLabel(track)}
                  selected={subtitlesEnabled && track.url === selectedSubtitleUrl}
                  onClick={() => {
                    onSubtitlesEnabledChange(true)
                    onSubtitleChange(track.url)
                    setMenuOpen(false)
                  }}
                />
              ))}
            </SubPanel>
          )}
        </div>
      ) : null}
    </div>
  )
}
