import type { Ref } from 'react'
import type { StreamSubtitle } from '@shared/types'

type Props = {
  videoRef: Ref<HTMLVideoElement>
  muted: boolean
  subtitles: StreamSubtitle[]
}

/** Media element + caption tracks (mode controlled by useTextTracks). */
export function VideoElement({ videoRef, muted, subtitles }: Props) {
  return (
    <video
      ref={videoRef}
      className="h-full w-full"
      playsInline
      preload="auto"
      muted={muted}
    >
      {subtitles.map((track) => (
        <track
          key={track.url}
          kind="subtitles"
          label={
            track.languageName
              ? `${track.languageName}${track.autoGenerated ? ' (auto)' : ''}`
              : track.languageCode
          }
          srcLang={track.languageCode}
          src={track.url}
        />
      ))}
    </video>
  )
}
