/** SiaTube stream API domain types (normalized, client-facing). */

/**
 * Playback track embedded in a quality option.
 * Only fields the client reads are kept in the API response.
 */
export type StreamEntry = {
  url: string
  /** Used with QualityOption.isHls for HLS detection. */
  isM3u8?: boolean
  /** Codec hint for preferred-quality selection (AVC vs VP9/AV1). */
  vcodec?: string
  /** Container hint for preferred-quality selection. */
  ext?: string
}

/** Selectable quality option for the UI (muxed, video-only + audio, or HLS). */
export type QualityOption = {
  /** Stable key for React / select value */
  id: string
  label: string
  height?: number
  /** Progressive muxed (single URL with audio+video) */
  isMuxed: boolean
  /** HLS / m3u8 — play via hls.js or native Safari */
  isHls: boolean
  /** Adaptive master playlist (hls_variant) vs fixed-quality playlist */
  isAdaptiveHls?: boolean
  video: StreamEntry
  audio?: StreamEntry
}

export type StreamSubtitle = {
  languageCode: string
  languageName?: string
  url: string
  autoGenerated?: boolean
}

/** Playback-only payload. Metadata (id/title) comes from the watch API. */
export type StreamPayload = {
  qualities: QualityOption[]
  subtitles: StreamSubtitle[]
}
